USE DATABASE RETAIL_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE SALES_CURATED AS
SELECT
    s.ORDER_ID, s.ORDER_DATE, s.SHIP_DATE, s.SHIP_MODE, s.CUSTOMER_ID, c.CUSTOMER_NAME, c.SEGMENT, c.CITY,c.STATE, c.REGION, s.PRODUCT_ID, 
p.PRODUCT_NAME, p.CATEGORY, p.SUB_CATEGORY, 
s.SALES, s.QUANTITY, s.DISCOUNT, s.PROFIT
FROM RETAIL_DB.RAW.SALES_RAW s
LEFT JOIN RETAIL_DB.RAW.CUSTOMERS_RAW c
ON s.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN RETAIL_DB.RAW.PRODUCTS_RAW p
ON s.PRODUCT_ID = p.PRODUCT_ID;

SELECT COUNT(*) FROM CURATED.SALES_CURATED;
DESC TABLE CURATED.SALES_CURATED;
