USE DATABASE RETAIL_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE PROCEDURE REFRESH_SALES_CURATED()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    CREATE OR REPLACE TABLE CURATED.SALES_CURATED AS
    SELECT
    s.ORDER_ID, s.ORDER_DATE, s.SHIP_DATE,s.SHIP_MODE, s.CUSTOMER_ID,
    c.CUSTOMER_NAME, c.SEGMENT, c.CITY, c.STATE, c.REGION,
    s.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.SUB_CATEGORY,
    s.SALES,s.QUANTITY,s.DISCOUNT,s.PROFIT
    FROM RAW.SALES_RAW s
    LEFT JOIN RAW.CUSTOMERS_RAW c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
    LEFT JOIN RAW.PRODUCTS_RAW p
    ON s.PRODUCT_ID = p.PRODUCT_ID;
    RETURN 'SALES_CURATED REFRESHED';

END;
$$;

CALL REFRESH_SALES_CURATED();