USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

-- RAW_CUSTOMER_TABLE

CREATE OR REPLACE TABLE SALES_RAW
(
    ORDER_ID STRING,
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    SHIP_MODE STRING,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    SALES NUMBER(10,2),
    QUANTITY INTEGER,
    DISCOUNT NUMBER(5,2),
    PROFIT NUMBER(10,2)
);

-- RAW_PRODUCTS_TABLE

CREATE OR REPLACE TABLE PRODUCTS_RAW
(
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING
);

-- RAW_INVENTORY_TABLE

CREATE OR REPLACE TABLE INVENTORY_RAW
(
    PRODUCT_ID STRING,
    STOCK_QUANTITY INTEGER,
    REORDER_LEVEL INTEGER,
    LAST_UPDATED DATE
);

SHOW TABLES;



