USE DATABASE RETAIL_DB;
USE SCHEMA RAW;

-- COPY INTO SALES_RAW

COPY INTO SALES_RAW
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (TYPE = CSV, PARSE_HEADER = TRUE)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT (*) FROM SALES_RAW;

SELECT *FROM SALES_RAW
LIMIT 10;

-- COPY INTO CUSTOMERS_RAW

COPY INTO CUSTOMERS_RAW
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (TYPE= CSV, PARSE_HEADER= TRUE)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT(*) FROM CUSTOMERS_RAW;

-- COPY INTO PRODUCTS_RAW

COPY INTO PRODUCTS_RAW
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (TYPE= CSV, PARSE_HEADER= TRUE, FIELD_OPTIONALLY_ENCLOSED_BY= '"')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT(*) FROM PRODUCTS_RAW;

-- COPY INTO INVENTORY_RAW

COPY INTO INVENTORY_RAW
FROM @RETAIL_STAGE/inventory.csv
FILE_FORMAT = (TYPE= CSV, PARSE_HEADER= TRUE)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT(*) FROM INVENTORY_RAW;
