USE DATABASE RETAIL_DB;

CREATE OR REPLACE TASK REFRESH_SALES_TASK
WAREHOUSE = RETAIL_WH
SCHEDULE = '5 MINUTE'
WHEN
SYSTEM$STREAM_HAS_DATA('RETAIL_DB.RAW.SALES_RAW_STREAM')
AS
CALL REFRESH_SALES_CURATED();

SHOW TASKS;
ALTER TASK REFRESH_SALES_TASK RESUME;