-- Create Warehouse
CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- Create Database
CREATE OR REPLACE DATABASE RETAIL_DB;

-- Create Schema
CREATE OR REPLACE SCHEMA RETAIL_DB.RAW;
CREATE OR REPLACE SCHEMA RETAIL_DB.CURATED;
CREATE OR REPLACE SCHEMA RETAIL_DB.ANALYTICS;